### ISSUE TITLE
Add More Styles and Patterns

### ISSUE THREAD

**Issue by EriKWDev** [EriKWDev/nanim#6]
One thing I want to be able to do with nanim is to replicate some of the amazing art pieces that I have saved on my pinterest here https://www.pinterest.se/ErikWGren/animation/

Many of them utilize textures and gradients to create a unique look. I want nanim to support textures and patterns and a lot of those same concepts. 

### Todo
- [ ] "Noisy Gradients" https://graphicdesign.stackexchange.com/questions/82074/research-grainy-noisy-gradient
- [x] Grids
- [ ] Water Color Effects
- [ ] Oil Color Effects
- [ ] Textures (Repeating and Non-repeating)
- [ ] "Entities as fill/stroke"
- [ ] "Scenes as fill/stroke"

**Comment by EriKWDev** [comment]
The way nanim does patterns is very hacky. I beleive it clears the context  and saves the pixels it cleared, then draws the pattern, saves the pattern's pixels and redraws the original ones. It at least used to work like that in my initial implementation, but I might have changed it down the line.

If that still is the way it works it obviously needs to change xD
